INSERT INTO grupos (miembros, estilo, origen, nombre, imagen, descripcion, subtexto) VALUES ('6', 'R&B/Soul', 'Gijón', 'The Soulers', '../img/the-soulers.jpg', 'The Soulers es una banda asturiana formada por Esther Yuste (voz), Sonsoles Rodríguez (teclados y coros), Alfonso Castrillo (batería), Gustavo Pérez (guitarra y coros), José R. Ibáñez (bajo) y Kiko Flores (saxo). Sus seis componentes proceden de distintos mundos y estilos musicales a nivel profesional, lo que proporciona una versatilidad y un eclecticismo que quedan reflejados en su primer trabajo ‘From side to side’.', 'No te lo puedes perder');
INSERT INTO grupos (miembros, estilo, origen, nombre, imagen, descripcion, subtexto) VALUES ('4', 'Rock', 'Oviedo', 'The Electric Buffalo', '../img/the-electric-buffalo.jpg', 'The Electric Buffalo es una banda de Oviedo que ha de lidiar con un comentario recurrente y no necesariamente negativo: No parecéis de aquí. La cosa es que son un grupo que transciende el Rock Sureño que les identifica con un sonido más propio de la tradición americana, y en el caso de su último disco hasta la fecha “Patrolman” (Boomerang, 2023), han hecho un homenaje a su bajista fundador, el tristemente desaparecido Alejandro Espina ( también miembro de Ilegales), que no sólo pellizca por lo sentido sino que les ha llevado a un nivel de composición y sonido sobresaliente. Álvaro Bárcena (voz y guitarra), Wilón de Calle (batería), Sergio Tutu, quien también hace las veces de productor, y Sam Rodríguez (teclados) aúnan su buen hacer para deleitarnos con su sonido', 'Disfruta de su atronador directo'); 
INSERT INTO grupos (miembros, estilo, origen, nombre, imagen, descripcion, subtexto) VALUES ('4', 'Rock', 'Gijón', 'Ojo de Loca', '../img/ojo-de-loca.jpg', 'En el universo de la música, surge una nueva fuerza que fusiona la experiencia de músicos veteranos con la frescura de la innovación. Les presentamos con orgullo a Ojo de Loca, un proyecto único que combina la maestría de músicos con una larga trayectoria en la escena musical con la energía y la creatividad de la nueva generación. Cada miembro de Ojo de Loca aporta décadas de experiencia en el escenario y en el estudio, habiendo compartido momentos inolvidables con algunas de las bandas más icónicas de la escena musical. Juntos, han creado una sinergia musical que lleva la música a nuevas alturas.', 'Presentando su primer trabajo');
INSERT INTO grupos (miembros, estilo, origen, nombre, imagen, descripcion, subtexto) VALUES ('0', 'Christmas Jam', 'Asturias', 'CHRYSTMAS JAM 2023', '../img/xmas-jam.jpg', 'El primer "Xmas Jam" es un espectáculo que nace en Asturias con la intención de seguir la estela de esos festivales de rock clásico que surgieron en Estados Unidos alrededor de una serie de bandas que, si bien tienen un gran número de seguidores, no pertenecen a la corriente mayoritaria musical de la industria. Estas bandas, tienen la peculiaridad de que una gran parte de sus conciertos (especialmente la dedicada a los solos) era improvisada, y por tanto, cada vez que se les veía era un espectáculo único. Es más, esta particular escena musical, al contrario que la de masas, tiene una serie de peculiaridades como permitir al público que grabe sus largos directos y los comparta con más gente, ganando nuevos seguidores con ello y fidelizando a los ya asistentes.', 'Sólo tienes una oportunidad');

INSERT INTO conciertos (fecha, hora, idgrupo, plazas, precioanticipado, preciotaquilla, intro) VALUES ('2024-11-10', '20:30', 1, '400', 45, 60, 'Some quick example text to build on the card title and make up the bulk of the card''s content.');
INSERT INTO conciertos (fecha, hora, idgrupo, plazas, precioanticipado, preciotaquilla, intro) VALUES ('2024-11-30', '22:30', 2, '396', 50, 60, 'Some quick example text to build on the card title and make up the bulk of the card''s content.');
INSERT INTO conciertos (fecha, hora, idgrupo, plazas, precioanticipado, preciotaquilla, intro) VALUES ('2024-12-29', '19:30', 4, '500', 40, 50, 'Some quick example text to build on the card title and make up the bulk of the card''s content.');
INSERT INTO conciertos (fecha, hora, idgrupo, plazas, precioanticipado, preciotaquilla, intro) VALUES ('2024-12-22', '21:30', 1, '500', 40, 50, 'Some quick example text to build on the card title and make up the bulk of the card''s content.');

INSERT INTO roles (nombre) VALUES ('ROLE_ADMIN');
INSERT INTO roles (nombre) VALUES ('ROLE_USER');

INSERT INTO usuarios (dni, username, apellidos, password, email, fechanacimiento, idrol, fecharegistro) VALUES ('10880331C', 'Pilar', 'Fernández', '$2a$10$LGNROB2dz.wjU50QDfvcpOkcZXyUnEt0oQaakELTZewsAg3cd3t26', 'pilar@pilar.com', '1975-03-09', 1, '2020-10-2');
INSERT INTO usuarios (dni, username, apellidos, password, email, fechanacimiento, idrol, fecharegistro) VALUES ('09879111A', 'Antonio', 'Banderas', '$2a$10$LGNROB2dz.wjU50QDfvcpOkcZXyUnEt0oQaakELTZewsAg3cd3t26', 'antonio@antonio.com','1960-01-30', 2, '2021-12-5');
INSERT INTO usuarios (dni, username, apellidos, password, email, fechanacimiento, idrol, fecharegistro) VALUES ('11258444K', 'Lola', 'Flores', '$2a$10$LGNROB2dz.wjU50QDfvcpOkcZXyUnEt0oQaakELTZewsAg3cd3t26', 'lola@lola.com','2000-05-03', 2, '2022-8-12');

INSERT INTO ventas (numeroentradas, fechaventa, horaventa, idusuario, idconcierto) VALUES (4, '2024-10-04', '21:11', 2, 2);


